### ISSUE TITLE
undefined reference error and test failed

### ISSUE THREAD

**Issue by Kyuber1007** [Xavier-Maruff/wgeo#1]
Now I'm trying to use wgeo, but there are some problems.

**First**, I'm done with building and installing, but, I can't do testing. 
I wrote my own google API key of course. 
When I try to run testing with  "sudo ./tools/test.sh {{ Debug || Release || undefined }}" command, the result is like below.

    Start 2: api_success.get_location
2/2 Test #2: api_success.get_location .........***Failed    2.31 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   2.32 sec

The following tests FAILED:
          2 - api_success.get_location (Failed)
Errors while running CTest

Command 'Release' not found, did you mean:

  command 'release' from deb bikeshed (1.78-0ubuntu1)

Try: sudo apt install <deb name>

undefined: command not found

**Second**, then I tried to run examples,there are undefined reference error.
My command steps are 
1. cmake ./
2. make

The error messages are,
[ 16%] Building C object CMakeFiles/c_example_shared.dir/example_shared.c.o
[ 33%] Linking C executable c_example_shared
[ 33%] Built target c_example_shared
[ 50%] Building CXX object CMakeFiles/cxx_example.dir/example.cpp.o
[ 66%] Linking CXX executable cxx_example
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libwgeo_static.a(get_wap.cpp.o): in function `get_wap_info(std::vector<wap_data, std::allocator<wap_data> >&)':
get_wap.cpp:(.text+0x1ae): undefined reference to `iw_get_range_info'
/usr/bin/ld: get_wap.cpp:(.text+0x462): undefined reference to `iw_init_event_stream'
/usr/bin/ld: get_wap.cpp:(.text+0x485): undefined reference to `iw_extract_event_stream'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cxx_example.dir/build.make:86: cxx_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/cxx_example.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Can you give me any help or advice?

**Comment by Xavier-Maruff** [comment]
Hi,
Thanks for your interest in the library!
There are a couple of issues I think might be causing your errors:

1. The command to run the tests actually doesn't accept any arguments - this is a mistake in the readme
2. Your compiler can't find `libiw` - if you install `libiw-dev` and `libiw30` this should be solved. This is my bad actually, I think I said in the readme that it needs to link against `libnl` instead of `libiw`

Also, it's probably easier if you build the library by running `./tools/build.sh Debug` or `./tools/build.sh Release` rather than manually running CMake, as it sets up the build directory for you.

To fix this issue, build, test, and install, run the following commands:
```bash
#ensure your key is being loaded by the test suite
echo "MY_API_KEY_HERE" > ./tools/env.txt
#install the needed libs
sudo apt install libiw-dev libiw30 -y
#build the library
./tools/build.sh Release
#run the tests from the base directory
sudo ./build/tests/wgeo_tests
#install the library
sudo cp -r include/wgeo /usr/include
sudo cp lib/* /usr/lib
```
Let me know how you go :)

**Comment by Kyuber1007** [comment]
Thank you for quick reply.

Even though I followed steps that you said, but, there are still errors.
So, I have some questions.

First, are there any differences betweenm "sudo ./build/tests/wgeo_tests" and "sudo ./tools/test.sh"?
The results are different. 
```
$ sudo ./build/tests/wgeo_tests
Running main() from wgeo/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from api_success
[ RUN      ] api_success.set_api_req
[       OK ] api_success.set_api_req (0 ms)
[ RUN      ] api_success.get_location
[       OK ] api_success.get_location (1973 ms)
[----------] 2 tests from api_success (1973 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1973 ms total)
[  PASSED  ] 2 tests.
```

```
$ sudo ./tools/test.sh
    Start 1: api_success.set_api_req
1/2 Test #1: api_success.set_api_req ..........***Failed    0.00 sec
    Start 2: api_success.get_location
2/2 Test #2: api_success.get_location .........***Failed    1.41 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   1.41 sec

The following tests FAILED:
          1 - api_success.set_api_req (Failed)
          2 - api_success.get_location (Failed)
Errors while running CTest
```

Second, after installing with the method you said(sudo cp things), I tried to get my real location with example.cpp, but it doesn't work because of undefined reference.
In wgeo/examples directory, I used command below.

```
$ cmake ./
-- Configuring done
-- Generating done
-- Build files have been written to: /wgeo/examples

$ make
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libwgeo_static.a(get_wap.cpp.o): in function `get_wap_info(std::vector<wap_data, std::allocator<wap_data> >&)':
get_wap.cpp:(.text+0x11b): undefined reference to `iw_get_range_info'
/usr/bin/ld: get_wap.cpp:(.text+0x2c2): undefined reference to `iw_init_event_stream'
/usr/bin/ld: get_wap.cpp:(.text+0x2df): undefined reference to `iw_extract_event_stream'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cxx_example.dir/build.make:86: cxx_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/cxx_example.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

How can I solve that problems..?
I really want to get my location(lat, long) with wgeo..

**Comment by Kyuber1007** [comment]
Also in directory /wgeo/build/examples there are files after build.
The files are 
c_example  c_example_shared  CMakeFiles  cmake_install.cmake  cxx_example  Makefile

How can I use those files?

**Comment by Xavier-Maruff** [comment]
The difference between `sudo ./tools/test.sh` and `sudo ./build/tests/wgeo_tests` is nothing anymore, but the commit you cloned had an error in the tools/test.sh script which ran the tests from a directory where it could not load the API key - that's why the tests are failing when you run them through tools/test.sh. 

Don't run CMake directly from one of the subdirectories - running the build script will automatically build all targets for you, including the library, the tests, and the examples.
When you run CMake from the examples subdirectory, you won't be linking against the correct libraries, as they are injected from the root CMakeLists.txt.
The files in the `build/examples` directory *are* those compiled examples - for example, if you want to run the C++ example, run `sudo ./build/examples/cxx_example`.

Hope this helps.

**Comment by Kyuber1007** [comment]
I succeed to get my location by running `sudo ./build/examples/cxx_example`.
Thank you for advice..

But, is there any method to use wgeo library in general file?
For example, not running by 'sudo ./build/exmaples/cxx_example', I want to use wgeo_set_api_req() and wgeo_get_location() in other directory, in other files. 
If i want to use the wgeo api in other files, how can I do that?

**Comment by Xavier-Maruff** [comment]
To use the library in your project, you just need to include the headers into your project, and link against both wgeo and libiw.
The install step I outlined in the readme puts the static library and headers into places where your compiler can find them, to simplify this process.

**Comment by Kyuber1007** [comment]
Thank you for replying me.

**Comment by Xavier-Maruff** [comment]
Happy to
